AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Properties:
      Timeout: 10
      MemorySize: 256
      Events:
        GetApiBye:
          Properties:
            ApiId: !Ref 'HttpApi'
            Method: GET
            Path: /api/bye
            TimeoutInMillis: 10000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
        GetHello:
          Properties:
            ApiId: !Ref 'HttpApi'
            Method: GET
            Path: /hello
            TimeoutInMillis: 10000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
      Runtime: nodejs16.x
      CodeUri: awesome-login/target/universal/awesome-login-0.1.0-SNAPSHOT.zip
      Handler: awesome-login.handler
    Type: AWS::Serverless::Function
  HttpApi:
    Properties:
      StageName: $default
    Type: AWS::Serverless::HttpApi
Outputs:
  Url:
    Description: Base URL of your endpoints
    Value:
      Fn::Sub: https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}
